<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="PrivacyPolicy.aspx.cs" Inherits="Web_App_Master.PrivacyPolicy" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class=" bg-white fg-black">
        Data privacy

The operators of this website take the protection of your personal data very seriously. We treat your personal data confidentially and in accordance with the data protection regulations as set down in law and this privacy statement. 

We will not process any of your personal data unless: 

You have expressly consented to this in advance. 
Processing your personal data is required in order to fulfil or complete a contract in which you are involved. 
We are required to process the data due to a legal obligation imposed upon us, or in order to protect your vital interests or the vital interests of another person.  Or
Processing your data is required in order to protect our prevailing legitimate interests or those of another party. 

It is generally possible to use our website without providing any personal data. If and when we do collect any personal data on our website (for example your name, address or email address), this is always on a voluntary basis wherever possible. This data will not be passed on to third parties without your express permission. 

We would like to advise that data transmitted over the Internet (e.g. when communicating via email) may be subject to security vulnerabilities. It is not possible to guarantee that data is completely protected against access by third parties. All of our employees are obligated to maintain data confidentiality. 


Server log files 

The provider of our website(s) automatically collects information sent to us by your browser and stores this in server log files. This information may include: 

Browser type/version
Operating system used
Referrer URL (last website you visited before visiting our website)
Host name of the computer accessing the website (IP address) and
The time of the server request 
This data is not consolidated with other data sources. We reserve the right to verify this data retrospectively if we are given reason to suspect illegal use.


Contact form

If you contact us using our contact form, the information given in the request form, including the contact information entered, will be stored by us for the purposes of processing the request and in case of follow-up questions. We will not share this data without your consent.


Cookies

"Cookies" are used on our website. Using cookies simplifies and accelerates your visit to our website. Cookies can be disabled in the settings menu of most browsers. 


Google Analytics

This website uses features provided by the online analysis service Google Analytics. The provider is Google Inc., 1600 Amphitheatre Parkway Mountain View, CA 94043, USA. Google Analytics uses "cookies". These are text files that are stored on your computer and allow us to analyse how you are using our website. The information generated by cookies about your use of the website is generally sent to a Google server in the USA and stored there. IP addresses are anonymised before being processed.


Browser plugin

You can prevent cookies from being stored by configuring the settings of your browser software; however, we would like to advise you that if you do so, you will not be able to use all of the functions on our website to their full extent. You can also prevent the data generated from the cookies relating to your use of the website (including your IP address) from being acquired by or processed by Google. To do so, click the link below and download and install the browser plugin: https://tools.google.com/dlpage/gaoptout


Preventing data collection

You can prevent Google Analytics from collecting your data by clicking on the following link. Doing so will set an opt-out cookie that will prevent your data from being collected on any future visits to this website: Disable Google Analytics. For more information on how Google Analytics processes user data, please refer to Google's privacy policy: https://support.google.com/analytics/answer/6004245?hl=en


reCAPTCHA

To protect your requests sent via an online form, we use the reCAPTCHA service provided by Google Inc. (Google). This check is used to distinguish whether a human has input the data or whether the website is being misused by an automated, machine-based process. 

The check includes sending your IP address to Google. If necessary, additional data required by Google for the reCAPTCHA service may also be sent. For this purpose, the information you enter is transmitted to Google, where it will be used further. However, Google shortens your IP address within member states of the European Union or other states party to the Agreement on the European Economic Area before use. Only in exceptional cases will a complete IP address be sent to a Google server in the USA and shortened there. Google uses this information on behalf of the operator of this website in order to evaluate your use of the website. The IP address transmitted by your browser for the purposes of reCAPTCHA is not consolidated with other data by Google. Processing of this data is subject to the Google-specific privacy policy. For more information about the Google privacy policy, please visit: https://policies.google.com/privacy


Google Maps

This site uses Google Maps via an API. The provider is Google Inc., 1600 Amphitheatre Parkway Mountain View, CA 94043, USA. In order to use the functions of Google Maps, it is necessary to store your IP address. This information is generally sent to a Google server in the USA and stored there. The provider of this website cannot influence the transmission of this data.

For more information on how Google processes your user data, please refer to Google's privacy policy: https://policies.google.com/privacy


SSL encryption

This website uses SSL encryption for security purposes and in order to ensure that confidential information is transmitted securely, for example the requests sent to us as a website operator. You can identify an encrypted connection as the web address starts with "https://" rather than "http://" and a padlock symbol is displayed in the address bar. In principle, the data that you transmit to us cannot be read by third parties if SSL encryption is enabled.


Processing data (customer and contract data)

We collect, process and use personal data only where this is required for the purposes of establishing, forming the content of or modifying a contract or legal relationship (existing data). If personal data is processed, it will be stored by us only as long as justified for the purpose of processing that data. We cannot stipulate a specific timeframe for which the data will be stored, as, for example, the time taken to execute and fulfil a contact can vary. As subsequent claims may arise from a contract in the future (e.g. in the event of defects), your data will be stored until the right of recourse for any possible subsequent claims has elapsed. 

We only collect, process and use personal data when you make use of our website (usage data) to the extent necessary to enable you to use the service or for invoicing.


Transmitting data upon the conclusion of a contract for services and digital content

We transmit personal data to third parties only if this is necessary in the context of executing the contract, for example to the credit institution responsible for processing payment.

We will not transmit your data any further unless you have expressly consented to this. We will not pass on your data to third parties, for example for the purposes of advertising, without your express consent.


    </div>
</asp:Content>
